# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ted Spectrum
email: 
description: > # this means to ignore newlines until "baseurl:"
  My awesome website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tedspectrum.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: tedspectrum

# Build settings
markdown: kramdown

# Plugin settings
plugins_dir: [jekyll-paginate]
plugins: [jekyll-paginate]
gems: [jekyll-paginate]
paginate: 6

# custom bits
theme: minima
header_pages:
  - assets/pages/sitemap.html
exclude: [package.json, package-lock.json]